#ifndef _LDE_CONFIG_H_
#define _LDE_CONFIG_H_

/* Generated by cmake */

#define PROJECT_VERSION "2.6.2"
#ifdef  PROJECT_VERSION
#define LDE_VERSION PROJECT_VERSION
#endif

#define HAVE_SIZEOF_OFF_T 1
#if HAVE_SIZEOF_OFF_T
#define SIZEOF_OFF_T 8
#endif

/* #undef ALPHA_CODE */
#define BETA_CODE 1
/* #undef JQDIR */
/* #undef NO_WRITE_INODE */
/* #undef PARANOID */
/* #undef READ_PART_TABLES */
/* #undef ERRORS_SAVED */

#define HAVE_DAYLIGHT 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_GETGRGID 1
#define HAVE_GETOPT_H 1
#define HAVE_GETOPT_LONG 1
#define HAVE_GETPWUID 1
#define HAVE_GRP_H 1
/* #undef HAVE_IO_H */
/* #undef HAVE_LSEEK64 */
#define HAVE_MEMMEM 1
#define HAVE_MEMMEM_GNU 1
/* #undef HAVE_O_BINARY */
#define HAVE_PWD_H 1
#define HAVE_SIGACTION 1
#define HAVE_SYNC 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TIMEZONE 1
#define HAVE_UNAME 1
#define HAVE_UNISTD_H 1

#if HAVE_O_BINARY
#else
#define O_BINARY 0
#endif

#define LDE_GNU_SOURCE 1
#if LDE_GNU_SOURCE
#define _GNU_SOURCE 1
#endif

/* #undef LDE_USE_LARGEFILE64 */
#if LDE_USE_LARGEFILE64
#define __USE_LARGEFILE64 1
#endif

#define CURSES_FOUND 1
#define CURSES_HAVE_NCURSES_H 1
#if CURSES_FOUND
#define HAVE_CURSES 1
#if CURSES_HAVE_NCURSES_H
#define NC_HEADER 1
#endif
#endif

#endif /* _LDE_CONFIG_H_ */
